# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Domain_Plugins.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Domain(object):
    def setupUi(self, Form_Domain):
        Form_Domain.setObjectName("Form_Domain")
        Form_Domain.resize(1276, 778)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_Domain.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form_Domain)
        self.gridLayout.setObjectName("gridLayout")
        self.domainplugins = QtWidgets.QTableWidget(Form_Domain)
        self.domainplugins.setMinimumSize(QtCore.QSize(200, 0))
        self.domainplugins.setSizeIncrement(QtCore.QSize(0, 0))
        self.domainplugins.setTabletTracking(False)
        self.domainplugins.setToolTip("")
        self.domainplugins.setStatusTip("")
        self.domainplugins.setAutoFillBackground(False)
        self.domainplugins.setStyleSheet("")
        self.domainplugins.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.domainplugins.setShowGrid(True)
        self.domainplugins.setGridStyle(QtCore.Qt.SolidLine)
        self.domainplugins.setWordWrap(True)
        self.domainplugins.setCornerButtonEnabled(True)
        self.domainplugins.setObjectName("domainplugins")
        self.domainplugins.setColumnCount(8)
        self.domainplugins.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.domainplugins.setHorizontalHeaderItem(7, item)
        self.domainplugins.horizontalHeader().setVisible(True)
        self.domainplugins.horizontalHeader().setCascadingSectionResizes(True)
        self.domainplugins.horizontalHeader().setDefaultSectionSize(150)
        self.domainplugins.horizontalHeader().setHighlightSections(False)
        self.domainplugins.horizontalHeader().setSortIndicatorShown(True)
        self.domainplugins.horizontalHeader().setStretchLastSection(True)
        self.domainplugins.verticalHeader().setVisible(False)
        self.domainplugins.verticalHeader().setCascadingSectionResizes(False)
        self.domainplugins.verticalHeader().setMinimumSectionSize(30)
        self.domainplugins.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.domainplugins, 0, 0, 1, 1)

        self.retranslateUi(Form_Domain)
        QtCore.QMetaObject.connectSlotsByName(Form_Domain)

    def retranslateUi(self, Form_Domain):
        _translate = QtCore.QCoreApplication.translate
        Form_Domain.setWindowTitle(_translate("Form_Domain", "子域名插件"))
        self.domainplugins.setSortingEnabled(True)
        item = self.domainplugins.horizontalHeaderItem(0)
        item.setText(_translate("Form_Domain", "ID"))
        item = self.domainplugins.horizontalHeaderItem(1)
        item.setText(_translate("Form_Domain", "插件名称"))
        item = self.domainplugins.horizontalHeaderItem(2)
        item.setText(_translate("Form_Domain", "插件位置"))
        item = self.domainplugins.horizontalHeaderItem(3)
        item.setText(_translate("Form_Domain", "插件作者"))
        item = self.domainplugins.horizontalHeaderItem(4)
        item.setText(_translate("Form_Domain", "插件Key1"))
        item = self.domainplugins.horizontalHeaderItem(5)
        item.setText(_translate("Form_Domain", "插件Key2"))
        item = self.domainplugins.horizontalHeaderItem(6)
        item.setText(_translate("Form_Domain", "插件Key3"))
        item = self.domainplugins.horizontalHeaderItem(7)
        item.setText(_translate("Form_Domain", "插件描述"))
