# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableWidget(object):
    def setupUi(self, TableWidget):
        TableWidget.setObjectName("TableWidget")
        TableWidget.resize(1009, 693)
        self.gridLayout = QtWidgets.QGridLayout(TableWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_result = QtWidgets.QTableWidget(TableWidget)
        self.tableWidget_result.setObjectName("tableWidget_result")
        self.tableWidget_result.setColumnCount(0)
        self.tableWidget_result.setRowCount(0)
        self.tableWidget_result.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget_result.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_result.verticalHeader().setVisible(False)
        self.tableWidget_result.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_result.verticalHeader().setHighlightSections(True)
        self.gridLayout.addWidget(self.tableWidget_result, 0, 0, 1, 2)
        self.pushButton_save = QtWidgets.QPushButton(TableWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 0, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(TableWidget)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout.addWidget(self.pushButton_exit, 1, 1, 1, 1)

        self.retranslateUi(TableWidget)
        self.pushButton_exit.clicked.connect(TableWidget.close)
        QtCore.QMetaObject.connectSlotsByName(TableWidget)

    def retranslateUi(self, TableWidget):
        _translate = QtCore.QCoreApplication.translate
        TableWidget.setWindowTitle(_translate("TableWidget", "子窗口"))
        self.tableWidget_result.setSortingEnabled(True)
        self.pushButton_save.setText(_translate("TableWidget", "保存"))
        self.pushButton_exit.setText(_translate("TableWidget", "取消"))
